### PR TITLE
Merge gmm md

### PR DESCRIPTION
**Pull request by gragusa**
Initial pull request

### CODE REVIEW

**Comment by sglyon** [comment]
This is a _huge_ PR!

**Comment by gragusa** [comment]
You think? :D

Giuseppe Ragusa

**Comment by gragusa** [comment]
I Will delete this PR was only to test the package.

Have you had a chance to dig through it?

**Comment by sglyon** [comment]
I haven't yet had a chance.

If you feel like you would like a second set of eyes on it, I can take a look. Otherwise I don't think I will get to it soon.

**Pull request closed without merging**
