### PR TITLE
Use the "optimal" form of the objective function in J_test

### PR DESCRIPTION
**Pull request by gragusa**
Addresses #13

### CODE REVIEW

**Comment by gragusa** [comment]
@spencerlyon2 I will merge if you are ok with it. 

Notice that I changed the way in which we handle the optimal_W --- depending on the IterationManager. If FirstStepGMM uses W directly and use the general form of the Variance Covariance Matrix

**Comment by sglyon** [comment]
@gragusa looks good to me.

One thing I don't quite see is where you implemented 

>  If FirstStepGMM uses W

**Comment by gragusa** [comment]
They are implemented [here](https://github.com/gragusa/GMM.jl/blob/master/src/GMM.jl#L259) and [here](https://github.com/gragusa/GMM.jl/blob/master/src/GMM.jl#L271). They are not part of this pull request. i implemented them and merged directly to master by error last week

**Comment by sglyon** [comment]
Ahh, I see. That makes more sense. Sounds good to me! Let's merge this!

**Comment by gragusa** [comment]
Waiting for travis to finish...

**Pull request merged**
